package org.bioconductor.packages.caAffy;

	/**
	* This file was auto-generated by R function 
	* createJavaBean Thu Feb 22 09:34:59 2007. 
	* It represents the S4 Class MeasuredBioAssayMatrix in R package caAffy. 
	*	A class representing a collection of
	*	measured expression values, with expression
	*	values stored as a matrix with rows corresponding
	*	to features and columns to samples.
	*/


public class MeasuredBioAssayMatrix implements java.io.Serializable  {
	private org.bioconductor.packages.rservices.RJNumericMatrix bioAssayData;

	public MeasuredBioAssayMatrix() {
		this.bioAssayData = new org.bioconductor.packages.rservices.RJNumericMatrix();
	}

	public MeasuredBioAssayMatrix(
		org.bioconductor.packages.rservices.RJNumericMatrix bioAssayData){

		this.bioAssayData = bioAssayData;
	}

	/**
	* Sets the bioAssayData value for this MeasuredBioAssayMatrix
	*
	* @param	bioAssayData	Numeric matrix with rows corresponding to
	*	features and columns to samples. Object of class
	*	"NumericMatrix"}
	*/
	public void setBioAssayData(org.bioconductor.packages.rservices.RJNumericMatrix bioAssayData) {
		this.bioAssayData = bioAssayData;
	}

	/**
	* Gets the bioAssayData value for this MeasuredBioAssayMatrix
	*
	* @return	the value of bioAssayData
	*	Numeric matrix with rows corresponding to
	*	features and columns to samples. Object of class
	*	"NumericMatrix"}
	*/
	public org.bioconductor.packages.rservices.RJNumericMatrix getBioAssayData() {
		return bioAssayData;
	}

	/**
	* Print this MeasuredBioAssayMatrix to String
	*
	* @return	contents of MeasuredBioAssayMatrix as a String
	*/
	public String toString() {
		StringBuffer res=new StringBuffer("{");
		res.append("bioAssayData=" + String.valueOf( bioAssayData ));
		res.append("}");
		return res.toString();
	}

	/**
	* Compare this MeasuredBioAssayMatrix with the input data.
	*
	* @param inputObject	the data to be compared with.
	* @return	true if the two have the same contents, false otherwise.
	*/
	public boolean equals(Object inputObject) {
		boolean res = getClass().equals(inputObject.getClass());
		if(res){
			MeasuredBioAssayMatrix obj = (MeasuredBioAssayMatrix)inputObject;
			Object inputBioAssayData = obj.getBioAssayData();
			if((bioAssayData==null)||(inputBioAssayData==null))
				res = res&&(bioAssayData==inputBioAssayData);
			else
				res = res&&bioAssayData.equals(inputBioAssayData);
		}
		return res;
	}

}
