package org.bioconductor.cagrid.caaffy.client;

import java.io.InputStream;
import java.rmi.RemoteException;

import javax.xml.namespace.QName;

import org.apache.axis.EngineConfiguration;
import org.apache.axis.client.AxisClient;
import org.apache.axis.client.Stub;
import org.apache.axis.configuration.FileProvider;
import org.apache.axis.message.addressing.EndpointReferenceType;
import org.apache.axis.types.URI.MalformedURIException;
import org.apache.axis.utils.ClassUtils;

import org.oasis.wsrf.properties.GetResourcePropertyResponse;

import org.globus.gsi.GlobusCredential;

import org.bioconductor.cagrid.caaffy.stubs.CaAffyPortType;
import org.bioconductor.cagrid.caaffy.stubs.service.CaAffyServiceAddressingLocator;
import org.bioconductor.cagrid.caaffy.common.CaAffyI;
import gov.nih.nci.cagrid.introduce.security.client.ServiceSecurityClient;

/**
 * This class is autogenerated, DO NOT EDIT GENERATED GRID SERVICE METHODS.
 *
 * This client is generated automatically by Introduce to provide a clean unwrapped API to the
 * service.
 *
 * On construction the class instance will contact the remote service and retrieve it's security
 * metadata description which it will use to configure the Stub specifically for each method call.
 * 
 * @created by Introduce Toolkit version 1.0
 */
public class CaAffyClient extends ServiceSecurityClient implements CaAffyI {	
	protected CaAffyPortType portType;
	private Object portTypeMutex;

	public CaAffyClient(String url) throws MalformedURIException, RemoteException {
		this(url,null);	
	}

	public CaAffyClient(String url, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(url,proxy);
	   	initialize();
	}
	
	public CaAffyClient(EndpointReferenceType epr) throws MalformedURIException, RemoteException {
	   	this(epr,null);
	}
	
	public CaAffyClient(EndpointReferenceType epr, GlobusCredential proxy) throws MalformedURIException, RemoteException {
	   	super(epr,proxy);
		initialize();
	}
	
	private void initialize() throws RemoteException {
	    this.portTypeMutex = new Object();
		this.portType = createPortType();
	}

	private CaAffyPortType createPortType() throws RemoteException {

		CaAffyServiceAddressingLocator locator = new CaAffyServiceAddressingLocator();
		// attempt to load our context sensitive wsdd file
		InputStream resourceAsStream = ClassUtils.getResourceAsStream(getClass(), "client-config.wsdd");
		if (resourceAsStream != null) {
			// we found it, so tell axis to configure an engine to use it
			EngineConfiguration engineConfig = new FileProvider(resourceAsStream);
			// set the engine of the locator
			locator.setEngine(new AxisClient(engineConfig));
		}
		CaAffyPortType port = null;
		try {
			port = locator.getCaAffyPortTypePort(getEndpointReference());
		} catch (Exception e) {
			throw new RemoteException("Unable to locate portType:" + e.getMessage(), e);
		}

		return port;
	}
	
	public GetResourcePropertyResponse getResourceProperty(QName resourcePropertyQName) throws RemoteException {
		return portType.getResourceProperty(resourcePropertyQName);
	}

	public static void usage(){
		System.out.println(CaAffyClient.class.getName() + " -url <service url>");
	}
	
	public static void main(String [] args){
	    System.out.println("Running the Grid Service Client");
		try{
		if(!(args.length < 2)){
			if(args[0].equals("-url")){
			  CaAffyClient client = new CaAffyClient(args[1]);
			  // place client calls here if you want to use this main as a
			  // test....
			} else {
				usage();
				System.exit(1);
			}
		} else {
			usage();
			System.exit(1);
		}
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(1);
		}
	}

	public org.bioconductor.cagrid.caaffy.DerivedBioAssays caExpresso(org.bioconductor.cagrid.caaffy.MeasuredBioAssays measuredBioAssays,org.bioconductor.cagrid.caaffy.ExpressoParameter expressoParameter) throws RemoteException {
      synchronized(portTypeMutex){
        configureStubSecurity((Stub)portType,"caExpresso");
        org.bioconductor.cagrid.caaffy.stubs.CaExpressoRequest params = new org.bioconductor.cagrid.caaffy.stubs.CaExpressoRequest();
        org.bioconductor.cagrid.caaffy.stubs.CaExpressoRequestMeasuredBioAssays measuredBioAssaysContainer = new org.bioconductor.cagrid.caaffy.stubs.CaExpressoRequestMeasuredBioAssays();
        measuredBioAssaysContainer.setMeasuredBioAssays(measuredBioAssays);
        params.setMeasuredBioAssays(measuredBioAssaysContainer);
        org.bioconductor.cagrid.caaffy.stubs.CaExpressoRequestExpressoParameter expressoParameterContainer = new org.bioconductor.cagrid.caaffy.stubs.CaExpressoRequestExpressoParameter();
        expressoParameterContainer.setExpressoParameter(expressoParameter);
        params.setExpressoParameter(expressoParameterContainer);
        org.bioconductor.cagrid.caaffy.stubs.CaExpressoResponse boxedResult = portType.caExpresso(params);
        return boxedResult.getDerivedBioAssays();
      }
    }
	public org.bioconductor.cagrid.caaffy.QaReport caQAReport(org.bioconductor.cagrid.caaffy.MeasuredBioAssays measuredBioAssays) throws RemoteException {
      synchronized(portTypeMutex){
        configureStubSecurity((Stub)portType,"caQAReport");
        org.bioconductor.cagrid.caaffy.stubs.CaQAReportRequest params = new org.bioconductor.cagrid.caaffy.stubs.CaQAReportRequest();
        org.bioconductor.cagrid.caaffy.stubs.CaQAReportRequestMeasuredBioAssays measuredBioAssaysContainer = new org.bioconductor.cagrid.caaffy.stubs.CaQAReportRequestMeasuredBioAssays();
        measuredBioAssaysContainer.setMeasuredBioAssays(measuredBioAssays);
        params.setMeasuredBioAssays(measuredBioAssaysContainer);
        org.bioconductor.cagrid.caaffy.stubs.CaQAReportResponse boxedResult = portType.caQAReport(params);
        return boxedResult.getQaReport();
      }
    }
	public gov.nih.nci.cagrid.metadata.security.ServiceSecurityMetadata getServiceSecurityMetadata() throws RemoteException {
      synchronized(portTypeMutex){
        configureStubSecurity((Stub)portType,"getServiceSecurityMetadata");
        gov.nih.nci.cagrid.introduce.security.stubs.GetServiceSecurityMetadataRequest params = new gov.nih.nci.cagrid.introduce.security.stubs.GetServiceSecurityMetadataRequest();
        gov.nih.nci.cagrid.introduce.security.stubs.GetServiceSecurityMetadataResponse boxedResult = portType.getServiceSecurityMetadata(params);
        return boxedResult.getServiceSecurityMetadata();
      }
    }

}
