package org.bioconductor.packages.caDNAcopy.service.globus;

import org.bioconductor.packages.caDNAcopy.service.CaDNAcopyImpl;

import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the CaDNAcopyImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correclty mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public class CaDNAcopyProviderImpl{
	
	CaDNAcopyImpl impl;
	
	public CaDNAcopyProviderImpl() throws RemoteException {
		impl = new CaDNAcopyImpl();
	}
	

    public org.bioconductor.packages.caDNAcopy.stubs.GetDerivedDNAcopySegmentResponse getDerivedDNAcopySegment(org.bioconductor.packages.caDNAcopy.stubs.GetDerivedDNAcopySegmentRequest params) throws RemoteException {
    org.bioconductor.packages.caDNAcopy.stubs.GetDerivedDNAcopySegmentResponse boxedResult = new org.bioconductor.packages.caDNAcopy.stubs.GetDerivedDNAcopySegmentResponse();
    boxedResult.setDerivedDNAcopySegment(impl.getDerivedDNAcopySegment(params.getDNAcopyAssays().getDNAcopyAssays(),params.getDNAcopyParameter().getDNAcopyParameter()));
    return boxedResult;
  }

}
