
package org.bioconductor.rserviceJms.services.caPROcess;
import java.io.*;
import java.util.*;

/**

 * caPROcessProperties defines the properties for caPROcess
 * auto-generated by R function getRWebServicesProperties, Mon Jan 22 14:12:15 2007
 */
public class caPROcessProperties extends Properties
{
	public caPROcessProperties() throws Exception
	{
		super();
		try{
			load(getClass().getResourceAsStream("RWebServices4java.properties"));
		} catch(IOException e){
			System.err.println(e.getMessage());
			throw new Exception("File RWebServices4java.properties not found.");
		}
	}
}
