package org.bioconductor.packages.biobase;

	/**
	* This file was auto-generated by R function 
	* createJavaBean Thu Feb 22 09:34:59 2007. 
	* It represents the S4 Class Versions in R package Biobase. 
	*	A class to record version number
	*	information. This class is used to report
	*	versions; to add version informaton to your own
	*	class, use object Versioned-class in R package .
	*/


public class Versions implements java.io.Serializable  {
	private Object[] rData;

	public Versions() {
		this.rData = new Object[]{};
	}

	public Versions(
		Object[] rData){

		this.rData = rData;
	}

	/**
	* Sets the rData value for this Versions
	*
	* @param	rData	
	*/
	public void setRData(Object[] rData) {
		this.rData = rData;
	}

	/**
	* Gets the rData value for this Versions
	*
	* @return	the value of rData
	*	
	*/
	public Object[] getRData() {
		return rData;
	}

	/**
	* Print this Versions to String
	*
	* @return	contents of Versions as a String
	*/
	public String toString() {
		StringBuffer res=new StringBuffer("{");
		res.append("rData=" + java.util.Arrays.toString( rData ));
		res.append("}");
		return res.toString();
	}

	/**
	* Compare this Versions with the input data.
	*
	* @param inputObject	the data to be compared with.
	* @return	true if the two have the same contents, false otherwise.
	*/
	public boolean equals(Object inputObject) {
		boolean res = getClass().equals(inputObject.getClass());
		if(res){
			Versions obj = (Versions)inputObject;
			Object inputRData = obj.getRData();
			if((rData==null)||(inputRData==null))
				res = res&&(rData==inputRData);
			else
				res = res&&java.util.Arrays.equals(rData, (Object[])inputRData);
		}
		return res;
	}

}
