package org.bioconductor.packages.caCGHcall.common;

import javax.xml.namespace.QName;


/**
 * This class is autogenerated, DO NOT EDIT
 *
 * @created by Introduce Toolkit version 1.3
 */
public interface CaCGHcallConstantsBase {
	public static final String SERVICE_NS = "http://caCGHcall.packages.bioconductor.org/CaCGHcall";
	public static final QName RESOURCE_KEY = new QName(SERVICE_NS, "CaCGHcallKey");
	public static final QName RESOURCE_PROPERTY_SET = new QName(SERVICE_NS, "CaCGHcallResourceProperties");
	public static final QName SERVICEMETADATA = new QName("gme://caGrid.caBIG/1.0/gov.nih.nci.cagrid.metadata", "ServiceMetadata");
	
}
