package org.bioconductor.packages.caCGHcall.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public interface CaCGHcallI {

  public org.oasis.wsrf.properties.GetMultipleResourcePropertiesResponse getMultipleResourceProperties(org.oasis.wsrf.properties.GetMultipleResourceProperties_Element params) throws RemoteException ;

  public org.oasis.wsrf.properties.GetResourcePropertyResponse getResourceProperty(javax.xml.namespace.QName params) throws RemoteException ;

  public org.oasis.wsrf.properties.QueryResourcePropertiesResponse queryResourceProperties(org.oasis.wsrf.properties.QueryResourceProperties_Element params) throws RemoteException ;

  /**
   * Method takes CGHcallAssays and CGHcallParameter as parameters and returns a DerivedCGHcallSegment using Bioconductor's CGHcall algorithm
   *
   * @param cGHcallAssays
   * @param cGHcallParameter
   */
  public org.bioconductor.cagrid.cacghcall.DerivedCGHcallSegment getDerivedCGHcallSegment(org.bioconductor.cagrid.cacghcall.CGHcallAssays cGHcallAssays,org.bioconductor.cagrid.cacghcall.CGHcallParameter cGHcallParameter) throws RemoteException ;

}

