
package org.bioconductor.rserviceJms.services.caDNAcopy;
import java.io.*;
import java.util.*;

/**

 * caDNAcopyProperties defines the properties for caDNAcopy
 * auto-generated by R function getRWebServicesProperties, Thu Feb 22 09:34:39 2007
 */
public class caDNAcopyProperties extends Properties
{
	public caDNAcopyProperties() throws Exception
	{
		super();
		try{
			load(getClass().getResourceAsStream("RWebServices4java.properties"));
		} catch(IOException e){
			System.err.println(e.getMessage());
			throw new Exception("File RWebServices4java.properties not found.");
		}
	}
}
