
package org.bioconductor.rserviceJms.services.caAffy;
import java.io.*;
import java.util.*;

/**

 * caAffyProperties defines the properties for caAffy
 * auto-generated by R function getRWebServicesProperties, Wed Feb 28 20:35:40 2007
 */
public class caAffyProperties extends Properties
{
	public caAffyProperties() throws Exception
	{
		super();
		try{
			load(getClass().getResourceAsStream("RWebServices4java.properties"));
		} catch(IOException e){
			System.err.println(e.getMessage());
			throw new Exception("File RWebServices4java.properties not found.");
		}
	}
}
