package org.bioconductor.packages.caCGHcall.service.globus;

import org.bioconductor.packages.caCGHcall.service.CaCGHcallImpl;

import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the CaCGHcallImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correclty mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public class CaCGHcallProviderImpl{
	
	CaCGHcallImpl impl;
	
	public CaCGHcallProviderImpl() throws RemoteException {
		impl = new CaCGHcallImpl();
	}
	

    public org.bioconductor.packages.caCGHcall.stubs.GetDerivedCGHcallSegmentResponse getDerivedCGHcallSegment(org.bioconductor.packages.caCGHcall.stubs.GetDerivedCGHcallSegmentRequest params) throws RemoteException {
    org.bioconductor.packages.caCGHcall.stubs.GetDerivedCGHcallSegmentResponse boxedResult = new org.bioconductor.packages.caCGHcall.stubs.GetDerivedCGHcallSegmentResponse();
    boxedResult.setDerivedCGHcallSegment(impl.getDerivedCGHcallSegment(params.getCGHcallAssays().getCGHcallAssays(),params.getCGHcallParameter().getCGHcallParameter()));
    return boxedResult;
  }

}
