package org.bioconductor.packages.caPROcess.service.globus;

import org.bioconductor.packages.caPROcess.service.CaPROcessImpl;

import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the CaPROcessImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correclty mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public class CaPROcessProviderImpl{
	
	CaPROcessImpl impl;
	
	public CaPROcessProviderImpl() throws RemoteException {
		impl = new CaPROcessImpl();
	}
	

    public org.bioconductor.packages.caPROcess.stubs.GetPeakLocationResponse getPeakLocation(org.bioconductor.packages.caPROcess.stubs.GetPeakLocationRequest params) throws RemoteException {
    org.bioconductor.packages.caPROcess.stubs.GetPeakLocationResponse boxedResult = new org.bioconductor.packages.caPROcess.stubs.GetPeakLocationResponse();
    boxedResult.setPeakLocation(impl.getPeakLocation(params.getMzAssays().getMzAssays(),params.getPROcessParameter().getPROcessParameter()));
    return boxedResult;
  }

}
