package org.bioconductor.packages.caPROcess;

	/**
	* This file was auto-generated by R function 
	* createJavaBean Mon Jan 22 14:12:15 2007. 
	* It represents the S4 Class MzSpectrum in R package caPROcess. 
	*/


public class MzSpectrum implements java.io.Serializable  {
	private String[] spectrumName;
	private double[] mzRatio;
	private double[] intensity;

	public MzSpectrum() {
		this.spectrumName = new String[]{};
		this.mzRatio = new double[]{};
		this.intensity = new double[]{};
	}

	public MzSpectrum(
		String[] spectrumName,
		double[] mzRatio,
		double[] intensity){

		this.spectrumName = spectrumName;
		this.mzRatio = mzRatio;
		this.intensity = intensity;
	}

	/**
	* Sets the spectrumName value for this MzSpectrum
	*
	* @param	spectrumName	
	*/
	public void setSpectrumName(String[] spectrumName) {
		this.spectrumName = spectrumName;
	}

	/**
	* Gets the spectrumName value for this MzSpectrum
	*
	* @return	the value of spectrumName
	*	
	*/
	public String[] getSpectrumName() {
		return spectrumName;
	}

	/**
	* Sets the mzRatio value for this MzSpectrum
	*
	* @param	mzRatio	
	*/
	public void setMzRatio(double[] mzRatio) {
		this.mzRatio = mzRatio;
	}

	/**
	* Gets the mzRatio value for this MzSpectrum
	*
	* @return	the value of mzRatio
	*	
	*/
	public double[] getMzRatio() {
		return mzRatio;
	}

	/**
	* Sets the intensity value for this MzSpectrum
	*
	* @param	intensity	
	*/
	public void setIntensity(double[] intensity) {
		this.intensity = intensity;
	}

	/**
	* Gets the intensity value for this MzSpectrum
	*
	* @return	the value of intensity
	*	
	*/
	public double[] getIntensity() {
		return intensity;
	}

	/**
	* Print this MzSpectrum to String
	*
	* @return	contents of MzSpectrum as a String
	*/
	public String toString() {
		StringBuffer res=new StringBuffer("{");
		res.append("spectrumName=" + java.util.Arrays.toString( spectrumName ));
		res.append(", ");
		res.append("mzRatio=" + java.util.Arrays.toString( mzRatio ));
		res.append(", ");
		res.append("intensity=" + java.util.Arrays.toString( intensity ));
		res.append("}");
		return res.toString();
	}

	/**
	* Compare this MzSpectrum with the input data.
	*
	* @param inputObject	the data to be compared with.
	* @return	true if the two have the same contents, false otherwise.
	*/
	public boolean equals(Object inputObject) {
		boolean res = getClass().equals(inputObject.getClass());
		if(res){
			MzSpectrum obj = (MzSpectrum)inputObject;
			Object inputSpectrumName = obj.getSpectrumName();
			if((spectrumName==null)||(inputSpectrumName==null))
				res = res&&(spectrumName==inputSpectrumName);
			else
				res = res&&java.util.Arrays.equals(spectrumName, (String[])inputSpectrumName);
			Object inputMzRatio = obj.getMzRatio();
			if((mzRatio==null)||(inputMzRatio==null))
				res = res&&(mzRatio==inputMzRatio);
			else
				res = res&&java.util.Arrays.equals(mzRatio, (double[])inputMzRatio);
			Object inputIntensity = obj.getIntensity();
			if((intensity==null)||(inputIntensity==null))
				res = res&&(intensity==inputIntensity);
			else
				res = res&&java.util.Arrays.equals(intensity, (double[])inputIntensity);
		}
		return res;
	}

}
